# Generated by Django 6.0.5 on 2026-05-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='projects/')),
                ('project_details', models.TextField(null=True)),
                ('github_repo', models.URLField()),
                ('live_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('backend', models.CharField(max_length=100)),
                ('apis', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='media/profile/')),
                ('college_name', models.CharField(max_length=100)),
                ('college_location', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=150)),
                ('bachelors_year', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('school_location', models.CharField(max_length=100)),
                ('school_year', models.CharField(max_length=50)),
            ],
        ),
    ]
