# Generated by Django 6.0.5 on 2026-05-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='desc',
        ),
    ]
