# Generated by Django 6.0.5 on 2026-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_skill_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='database',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='frontend',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='apis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='backend',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='others',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
